export default {
  host: "",
  before: 0,
  after: 0,
  enabledHover: true,
  syncHover: true,
  hoverX: null,
  navigation: "",
  syncPanning: true,
  panning: false,
  syncHighlight: true,
  highlighting: false,
  highlight: null,
  desiredUnits: "auto",
  syncUnits: true,
  unitsConversionMethod: "",
  unitsConversionDivider: -1,
  unitsConversionFractionDigits: 0,
  unit: "",
  temperature: "celsius",
  secondsAsTime: true,
  timezone: "default",
}
