export default {
  fullyLoaded: false,
  loaded: false,
  id: "",
  name: "",
  context: "",
  family: "",
  title: "",
  priority: 0,
  plugin: "",
  module: "",
  units: "",
  chartType: "",
  updateEvery: 0,
  firstEntry: 0,
  lastEntry: 0,
  dimensions: {},
  chartLabels: {},
}
